# Cranberry Clafoutis
_from Victoria Getis_
\begin{recipe}{Cranberry Clafoutis}{}{1 hr}
\freeform Heat the oven to 425 degrees. Butter a deep 9 or 10-inch pie plate. Sprinkle it with a tablespoon or so of sugar, then swirl dish to coat evenly. Invert to remove excess.
\ingredient[1]{tablespoon}{butter, for greasing pan}
\ingredient[1]{cup}{sugar}
\ingredient[2]{}{eggs}
\ingredient[1]{cup}{flour}
\ingredient[1]{cup}{half-and-half or whole milk}
\ingredient[Pinch]{}{salt}
\freeform Beat eggs well, then add remaining sugar. Beat until smooth. Add flour, and beat again until smooth. Add the half-and-half or milk and salt, and whisk until smooth.
\ingredient[2]{cups}{cranberries}
\ingredient{Scant cup}{}{walnuts}

\freeform Coarsely chop cranberries and walnuts. If using a food processor, do not overprocess -- just pulse until chopped. (It's very fast.) Put cranberry mixture in pie plate, and pour batter over it.
\ingredient[]{}{Confectioners' sugar}
\freeform Bake for about 30 minutes, or until clafoutis is nicely browned on top and a knife inserted into it comes out clean. Sift some confectioners' sugar over it, and serve warm or at room temperature.


\end{recipe}
<!-- Type: Dessert -->
<!-- Cook: Mark Bitman in the New York Times -->
