# Homemade Baked Mac and Cheese
_from Borchuluun Yadamsuren_
\begin{recipe}{Homemade Baked Mac and Cheese}{12 servings}{20 min}
\freeform
Instructions

Preheat oven to 350F. Lightly grease a large 3 qt or 4 qt baking dish and set aside.Combine shredded cheeses in a large bowl and set aside.
Cook the pasta one minute shy of al dente according to the package instructions. Remove from heat, drain, and place in a large bowl.
Drizzle pasta with olive oil and stir to coat pasta. Set aside to cool while preparing cheese sauce.
Melt butter in a deep saucepan, dutch oven, or stock pot.
Whisk in flour over medium heat and continue whisking for about 1 minute until bubbly and golden.
Gradually whisk in the milk and heavy cream until nice and smooth. Continue whisking until you see bubbles on the surface and then continue cooking and whisking for another 2 minutes. Whisk in salt and pepper.
Add two cups of shredded cheese and whisk until smooth. Add another two cups of shredded cheese and continue whisking until creamy and smooth. Sauce should be nice and thick.
Stir in the cooled pasta until combined and pasta is fully coated with the cheese sauce.
Pour half of the mac and cheese into the prepared baking dish. Top with remaining 2 cups of shredded cheese and then the remaining mac and cheese.
In a small bowl, combine panko crumbs, Parmesan cheese, melted butter and paprika. Sprinkle over the top and bake until bubbly and golden brown, about 30 minutes. Serve immediately.

\ingredient[16]{oz}{elbow macaroni, cooked (or other tubular pasta)}
\ingredient[1]{tbsp}{extra virgin olive oil}
\ingredient[6]{tbsp}{ unsalted butter}
\ingredient[1/3]{cup}{all purpose flour}
\ingredient[3]{cups}{whole milk}
\ingredient[1]{cup}{heavy whipping cream}
\ingredient[4]{cups}{sharp cheddar cheese shredded}
\ingredient[2]{cups}{Gruyere cheese shredded}
\ingredient[4]{tbsp}{butter melted}
\ingredient[1/2]{cups}{Parmesan cheese shredded}
\ingredient[1/4]{tbsp}{smoked paprika}
salt and pepper to taste

\freeform Add final notes, such as serving suggestions.
\end{recipe}
<!-- Type: Mac and Cheese --> <br>
<!-- Cook:Trish -->
