<!-- Type:Main Dish -->
<!-- Cook:ShelbyHatch -->

# Spinach-Ricotta Pie

\begin {recipe} {Spinach-Ricotta Pie} {4-6} {3 hours}
\freeform from The Moosewood Cookbook by Molly Katzen
\freeform Preheat oven to 375
\freeform The Crust
\ingredient [1] {cup} {flour}
\ingredient [\fr 13] {cup} {cold butter}

Cut together 1 cup flour (4/5 white plus 1/5 whole wheat is nice) and 1/3 cup cold butter. Use a pastry cutter or two forks, or a food processor fitted with a steel blade.

\ingredient [3] {Tbsp} {cold buttermilk}

When the mixture is uniformly blended, add about 3 tablespoons cold buttermilk - or enough so that the mixture holds together enough to form a ball.
\newstep

Chill the dough at least one hour.
\freeform The Filling
\ingredient [1] {lb} {ricotta cheese}
\ingredient [3] {} {beaten eggs}
\ingredient [1] {small} {diced onion}
\ingredient [3] {Tbsp} {flour}
\ingredient [\fr 12] {cup} {grated sharp cheese}
\ingredient [1] {dash} {nutmeg}

Mix everything together, blending well. Spread into unbaked pie shell. 

\ingredient [1] {cup} {sour cream}
\ingredient [] {} {paprika}

Top with 1 cup sour cream spread to the edges of the crust and a generous application of paprika.
\newstep

Bake in 375 oven for 40-45 minutes. Serve piping hot.

\end {recipe}
