# Creamy Turkey Noodle Soup
_from Jonathan Emery_
\begin{recipe}{Creamy Turkey Noodle Soup}{6 Servings}{30 minutes} %{Title}{Servings}{Prep time}
\freeform A soup that Mimi makes after Thanksgiving.       %Freeform formats a general comment.
\freeform\rule{\textwidth}{0.05pt}                         %Creates a nice horizontal rule.

%1st step ingredients---------------------------------------
    %\ingredient[quantity]{unit}{ingredient}
    %\Ingredient{ingredient and quantity}
\ingredient[3]{cups}{turkey}

%1st step action
Use leftover Thanksgiving turkey (or bake). Set aside.

%2nd step ingredients--------------------------------------
\ingredient[5]{tbsp}{butter}
\ingredient[2]{}{carrots}
\ingredient[1]{}{shallot}
\ingredient[1]{tbsp}{celery ceeds}

%2nd step action:
Saut\'{e} ingredients in butter for 5 minutes.

%3rd step ingredients--------------------------------------
\ingredient[\fr13]{cup}{flour} %\fr means fraction: so \fr13 = 1/3
\ingredient[32]{oz}{chicken broth}
\ingredient[\fr12]{cup}{half and half}
\ingredient[\fr12]{cup}{milk}

%3rd step action:
First stir in flour to saut\'{e}d vegetebles and then add liquids and bring mixture to a boil.

%4th step ingredients--------------------------------------
\ingredient[6]{oz}{Reames brand noodles}

%4th step action:
Add dry noodles to soup and simmer for about 20 minutes.

Cook orzo according to directions on package --- slightly al dente is fine as well. Drain and rise with cold water.

%5th step ingredients--------------------------------------
\ingredient[\fr14]{tsp}{salt}
\ingredient[\fr14]{tsp}{pepper}

Add salt and pepper to taste.

\freeform\rule{\textwidth}{0.05pt}

\freeform Good to eat for... weeks?

\end{recipe}
<!-- Type:Soup -->
<!-- Cook:JEmery -->
